syntax on
filetype plugin indent on
set termguicolors
map q :q<ENTER>
map w :w<ENTER>
" set clipboard+=unnamed
" set go+=a
" set pastetoggle=<F2>
" set clipboard=unnamedplus
" colo miramare
" colo camo
colo iceberg
set cursorline
set number
set relativenumber
" colo substrata
" colo gruvbox
set ls=0
set mouse=a
" type in spy and then enter for spell check
map spy :setlocal spell spelllang=en_us
" type in spn and then enter for nospell check
map spn :setlocal nospell
" If you've got NerdTree plugin, typing in ctrl+n will switch it on/off. Also
" the window size is set to 16, you can change that as your heart desires.
" :let g:NERDTreeWinSize=30
" let NERDTreeShowHidden=1
" :nnoremap <C-n> :NERDTreeToggle<CR>
" sets the colorscheme to gruvbox material and turns on spell check whenever
" you open a .md file
autocmd BufEnter *.md colorscheme gruvbox
autocmd BufEnter *.md setlocal spell spelllang=en_us
" autocmd BufEnter *.css set tabstop=2
" autocmd BufEnter *.css set shiftwidth=2
" autocmd BufEnter *.html set tabstop=2
" autocmd BufEnter *.html set shiftwidth=2
set noswapfile
